### ISSUE TITLE
 custom_lang.php overwriten during upgrade

### ISSUE THREAD

**Issue by switit** [InvoicePlane/InvoicePlane#991]
During upgrade of InvoicePlane by overwriting files to the existing ones, the custoem_lang.php file is also overwritten.
## Expected Behavior

custom_lang.php should be preserved on upgrade.
## Possible Solution

Rename custom_lang.php in the package to something like custom_lang.php.example
## Steps to Reproduce

1.unzip new version over the existing version
2.
3.
4.

**Comment by nielsdrost7** [comment]
Thanks for the bug report.
We'll fix this once we release the full 1.6.1 version.

**Comment by nielsdrost7** [comment]
Hey @switit we've just released version 1.6.1: https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6.1 and I double-checked to not include those pesky custom_lang, whatever it was. Can you check if this is what you meant?
I'm closing the issue, just let me know if you've still got your own custom_lang.php file

**Comment by switit** [comment]
Not fixed yet by v1.6.1
Extracting v1.6.1 over the existing ip folder resulted in the custom_lang.php file being replaced. You may either remove custom_lang.php from the package or if you want to maintain a template of the file, you may rename it to xustom_lang.php.example.

**Comment by nielsdrost7** [comment]
@switit I'll take a look this weekend.
Are you using the English language, that custom_language.php was overwritten?

**Comment by switit** [comment]
@nielsdrost7 Yes I'm using English language. Sorry I should have clarified that upfront.

**Comment by nielsdrost7** [comment]
No worries abd thanks for the clarification

**Comment by nielsdrost7** [comment]
@switit I've made a new version where custom_lang.php wasn't included (so it wouldn't overwrite your own custom_lang
But unfortunately, the installer was bugging out when the custom_lang.php wasn't there.

I'll take a look, to see what's going on.
